### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by mssmison** [TKoestlerx/sdexperiments#3]
Hi,

I'm running into the below any time I try and use this script.

Error completing request
Arguments: (0, 'a picture of dog\n', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=512x512 at 0x263100AB7C0>, None, None, None, 0, 20, 0, 4, 1, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, '', '', 5, '', 1390, False, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, -0.999969482421875, -170.99999809265137, 'Show/Hide Canvas', 0, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, None, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "C:\stablediffusion\stable-diffusion-webui\modules\ui.py", line 221, in f
    res = list(func(*args, **kwargs))
  File "C:\stablediffusion\stable-diffusion-webui\webui.py", line 63, in f
    res = func(*args, **kwargs)
  File "C:\stablediffusion\stable-diffusion-webui\modules\img2img.py", line 127, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\stablediffusion\stable-diffusion-webui\modules\scripts.py", line 286, in run
    processed = script.run(p, *script_args)
  File "C:\stablediffusion\stable-diffusion-webui\scripts\outpaint_region.py", line 366, in run
    newBase = Image.new("RGB", (newwidth, newheight), "black")
  File "C:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2806, in new
    return im._new(core.fill(mode, size, color))
TypeError: integer argument expected, got float

**Comment by TKoestlerx** [comment]
It seems to be this Line:

newBase = Image.new("RGB", (newwidth, newheight), "black") in the script.

You could try to write it as:
newwidth = int(newwidth)
newheight = int(newheight)
newBase = Image.new("RGB", (newwidth, newheight), "black")

Allthough i dont understand at what point the values turned float?
